version: 2.1

commands:
  prep:
    description: "Bring the repository up-to-date with master and handle setup"
    steps:
      - checkout
      - restore_cache:
          key: composer-{{ checksum "composer.lock" }}
      - run:
          name: Configure the CircleCI git user
          command: |
            git config --global user.email "ci@medology.com"
            git config --global user.name "Circle CI"
      - run:
          name: Configure git to use SSH instead of HTTP
          command: |
            git config --global url.git@github.com:.insteadOf git://github.com/
            git config --global --add url.git@github.com:.insteadOf https://github.com/
      - run:
          name: Add in submodules
          command: git submodule update --init
      - run:
          name: Run style fixer
          command: bin/ci-style-fixer
      - run:
          name: Merge master
          command: git fetch origin && git merge origin/master --no-edit
  test:
    description: "Set up and run tests"
    steps:
      - run:
          name: Start containers
          command: containers up -d
      - run:
          name: Initialize the project
          command: |
            mkdir -p ./artifacts
            bin/init_project
      - run:
          name: Behat test
          command: behat --strict -vv -f pretty -o std -f junit -o ./artifacts
      - store_test_results:
          path: artifacts
      - store_artifacts:
          path: artifacts

executors:
  ubuntu:
    environment:
      PATH: /opt/circleci/.pyenv/shims:./bin:./vendor/bin:./submodules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:./node_modules/.bin
    machine:
      image: ubuntu-2004:202010-01
    working_directory: /tmp/behat-google-place-autocomplete

jobs:
  test:
    executor: ubuntu
    parallelism: 1
    steps:
      - prep
      - test

workflows:
  version: 2
  test:
    jobs:
      - test
